# Error handling
server.error.include-message=always
spring.jackson.deserialization.fail-on-unknown-properties=true

# Import .env file variables
spring.config.import=optional:file:.env[.properties]

# Docker Postgres connection
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PSW}
spring.datasource.driver-class-name=org.postgresql.Driver

# Docker MongoDB connection
spring.data.mongodb.uri=mongodb+srv://phm:${MONGO_PSW}@phm2026.zjwtw2w.mongodb.net/phm?appName=phm2026

# Redis
spring.data.redis.url=${REDIS_URL}

# JPA and Hibernate settings
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#JWT
security.secret-key=${JWT_SECRET_KEY}
security.access-token-minutes=30
security.refresh-token-minutes=8

logging.level.root=INFO


#logging.level.org.springframework.data=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG